<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-12-24T12:53:09Z" name="Default suite" finished-at="2018-12-24T12:53:09Z" duration-ms="26">
    <groups>
    </groups>
    <test started-at="2018-12-24T12:53:09Z" name="Default test" finished-at="2018-12-24T12:53:09Z" duration-ms="26">
      <class name="com.authentication.Test1">
        <test-method signature="authenticationTest(java.lang.String)[pri:0, instance:com.authentication.Test1@e4487af]" started-at="2018-12-24T18:23:09Z" name="authenticationTest" data-provider="verify" finished-at="2018-12-24T18:23:09Z" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[Method public void com.authentication.Test1.authenticationTest(java.lang.String) throws java.lang.Exception requires a @DataProvider named : verify in class com.authentication.DataProvider]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: Method public void com.authentication.Test1.authenticationTest(java.lang.String) throws java.lang.Exception requires a @DataProvider named : verify in class com.authentication.DataProviderat org.testng.internal.Parameters.findDataProvider(Parameters.java:513)at org.testng.internal.Parameters.handleParameters(Parameters.java:691)at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:914)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- authenticationTest -->
      </class> <!-- com.authentication.Test1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
